framework: mocha
before_tests: gulp transpile
src_files:
    - node_modules/chai/chai.js
    - build/**/*.js
    - tests/setup.js
    - tests/test_*.js
watch_files:
    - js/**/*.js
    - tests/**/*.js
launch_in_dev:
    - phantomjs
