[package]
name = "integer_overflow"
version = "0.1.0"
authors = ["Emanuele Palazzetti <emanuele.palazzetti@gmail.com>"]
edition = "2018"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
